### ISSUE TITLE
Readme needs examples fixed

### ISSUE THREAD

**Issue by hereandnow** [midknight41/easy-swf#1]
First of all, i have to say that i like the module, and how you designed it. 

Your Readme isnt up to date, e.g.`acts.handleActivity` needs a version param now. the decider-function is `decider.handleWorkflow` now.

do you plan on developing/maintining that module further? i'm willing to contribute, but only if the module will be activly maintained!

**Comment by midknight41** [comment]
Thanks!

I admit I've been working on something else for a while and haven't been paying much attention to this. 

I'll have a look at the readme this week and update it to the current interface for starters. Happy to work together on it  going forward.

**Comment by midknight41** [comment]
fixed in https://github.com/midknight41/easy-swf/commit/7f87823c6b0d1771afdcda47bb6289064fd01407
