### ISSUE TITLE
AWS Config shouldn't be mandatory

### ISSUE THREAD

**Issue by hereandnow** [midknight41/easy-swf#2]
`WorkflowClient.prototype.validateConfig` shouldnt be necessary. AWS-SDK uses following environment-variables by default:

- AWS_ACCESS_KEY_ID
- AWS_SECRET_ACCESS_KEY
- AWS_REGION

read more about it [here](http://docs.aws.amazon.com/AWSJavaScriptSDK/guide/node-configuring.html)

currently i'm using your module like that to make it work:

    awsConfig = {
      accessKeyId: process.env.AWS_ACCESS_KEY_ID,
      secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
      region: process.env.AWS_REGION
   }

but i would like to strip that code. 

if you want your module to fail if config is totally missing you could do something like that:

    WorkflowClient.prototype.validateConfig = function (awsConfig) {
        if (!process.env.AWS_ACCESS_KEY_ID || !process.env.AWS_SECRET_ACCESS_KEY || !process.env.AWS_REGION) && awsConfig == null)
            throw new errors.NullArgumentError("awsConfig");
        if (!process.env.AWS_ACCESS_KEY_ID && awsConfig.accessKeyId == null)
            throw new errors.InvalidArgumentError("accessKeyId is mandatory");
        if (!process.env.AWS_SECRET_ACCESS_KEY && awsConfig.secretAccessKey == null)
            throw new errors.InvalidArgumentError("secretAccessKey is mandatory");
        if (!process.env.AWS_REGION && awsConfig.region == null)
            throw new errors.InvalidArgumentError("region is mandatory");
    };

what do you think?

**Comment by midknight41** [comment]
Looks like a good improvement! Happy to accept a PR.

Please note the code is in TypeScript so please update the .ts files.

**Comment by hereandnow** [comment]
i'm trying to implement this, but have problems with the typescript compilations. 

in your imports definition you refer to "C:\..." which of course is missing for me (i'm also on a mac)

if i try to use the definitions in `lib/typings`, the definition for nodeunit is missing. i then tried to use the one here "https://github.com/borisyankov/DefinitelyTyped", which does not work (don't know why though...)

would you mind providing a working `imports.d.ts`, i think it's best to put all definitions into 'lib/typings' and import from there. maybe you could even use [tds](http://definitelytyped.org/tsd/)?

**Comment by midknight41** [comment]
I'm redoing the project structure at present and moving to a structure compatible with DefinitelyTyped. I originally wrote this a while back and the tooling for node/TypeScript on Windows has improved a lot.

I'll make sure the output is cross-platform too.

I'm making a few changes to the package at present, notably removing the config for tasks, which I'll finish in a couple days I hope. I'll include your config change in that version.

**Comment by hereandnow** [comment]
great! ping in this ticket when you are done, and i will test the new structure on my mac if you want.

**Comment by midknight41** [comment]
@hereandnow - I've redone the project structure and have committed those changes now. Please note there were some breaking changes where I've tidied up some method signatures and simplified the config. The are documented in the README.md for your convenience.

I'll change the awsConfig as discussed next. They'll go into the next npm package.

**Comment by hereandnow** [comment]
nice work, i'll test stuff within the next few days!

**Comment by hereandnow** [comment]
looks like everything works, nice!

**Comment by midknight41** [comment]
I've added support for this now. If you wouldn't mind testing it out in a non-Windows environment that would be great. Assuming that works I'll publish to npm as v1.0.

FYI, I'll maintain strict semver going forward to avoid any accidental surprises!

**Comment by hereandnow** [comment]
i see what you did there, but i shouldn't be like that. the AWS-Config could contain more than just these 3 options. If you are sitting behind a proxy you could add the proxy-url via httpOptions. For example what i have to do to get outside of our proxy is to do this:

    var awsConfig = {
      sslEnabled: false,
      httpOptions: {
        proxy: 'our-proxy-url'
      }
    };

basically what you really should do is just check that each of these 3 properties should be set via config or env-vars

**Comment by midknight41** [comment]
You are right. I'll make it more specific.

**Comment by midknight41** [comment]
That should do it. If should only fail if it can't find any keys in the config or in process.env. config.update() is call if the passed is not null.

I also changed some other stuff under the hood to support parallel task execution. I doubt it'll affect anything you've been doing but it may be worth testing. It's not a breaking change but the way decision are submitted has been made more consistent.

I'll publish to npm once you test.

**Comment by hereandnow** [comment]
now it works properly, i think you can close this issue, and publish to npm. thanks for your effort!

**Comment by midknight41** [comment]
Published as 1.0.0. Thanks for the testing help and feedback!
